name: .NET Core - Release

on:
  push:
    branches: [ new-analysis, development ]
  pull_request:
    branches: [ new-analysis, development ]

jobs:
  release-net6:
    strategy:     
      matrix:
        runtimeIdentifier: [linux-x64, osx-x64, win-x64]
    name: Build Single-File Artifact
    runs-on: ubuntu-latest
    steps:
      - id: set-vars
        uses: actions/github-script@v5
        with:
          script: |
            core.setOutput("extension", "${{ matrix.runtimeIdentifier}}" === "win-x64" ? ".exe" : "");
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Restore
        run: dotnet restore -r ${{ matrix.runtimeIdentifier }}
      - name: Build
        working-directory: ./Cpp2IL/
        run: dotnet publish /p:Configuration=Release /p:TargetFramework=net6.0 /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishTrimmed=true /p:PublishgSingleFile=true /p:TrimMode=link --no-restore --self-contained -r ${{ matrix.runtimeIdentifier }}
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: Cpp2IL-net6-${{ matrix.runtimeIdentifier }}
          path: ./Cpp2IL/bin/Release/net6.0/${{ matrix.runtimeIdentifier }}/publish/Cpp2IL${{ steps.set-vars.outputs.extension }}
  release-netframework:
    name: Build - Windows .NET Framework Zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore -r win-x64
      - name: Build
        working-directory: ./Cpp2IL/
        run: dotnet publish /p:Configuration=Release /p:TargetFramework=net472 --no-restore -r win-x64
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Cpp2IL-Netframework472-Windows
          path: ./Cpp2IL/bin/Release/net472/win-x64/publish/
  tests:
    name: Run Tests & Publish Dev Package
    runs-on: ubuntu-latest
    steps:
      - id: set-vars
        uses: actions/github-script@v5
        with:
          script: |
            const gitHash = "$(git rev-parse --short "$GITHUB_SHA")";
            const gitBranch = "${GITHUB_REF#refs/heads/}";
            
            console.log(`Git Hash: ${gitHash}`);
            console.log(`Git Branch: ${gitBranch}`);
            
            core.setOutput("git_hash", gitHash);
            core.setOutput("git_branch", gitBranch);
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore /p:VersionSuffix=${{ steps.set-vars.outputs.git_branch }}-${{ steps.set-vars.outputs.git_hash }}
      - name: Run Tests
        run: dotnet test /p:Configuration=Release /p:VersionSuffix=${{ steps.set-vars.outputs.git_branch }}-${{ steps.set-vars.outputs.git_hash }}